CREATE DATABASE Pedidos;
USE Pedidos;

CREATE TABLE Estado(
  Id_Estado INT AUTO_INCREMENT PRIMARY KEY,
  Nombre_Estado VARCHAR(100) NOT NULL
);

CREATE TABLE Ciudades(
  Id_Ciudad INT AUTO_INCREMENT PRIMARY KEY,
  Ciudad_Cte VARCHAR(100) NOT NULL,
  CP_Cte CHAR(5) NOT NULL
);

CREATE TABLE Cliente(
  Id_Cte INT AUTO_INCREMENT PRIMARY KEY,
  RFC_Cte CHAR(13) NOT NULL,
  Nombre_Cte VARCHAR(150) NOT NULL,
  Direccion_Cte VARCHAR(200),
  Id_Estado INT NOT NULL,
  Id_Ciudad INT NOT NULL,
  FOREIGN KEY (Id_Estado) REFERENCES Estado(Id_Estado) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (Id_Ciudad) REFERENCES Ciudades(Id_Ciudad) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Producto(
  Id_Producto INT AUTO_INCREMENT PRIMARY KEY,
  Descripcion_Producto VARCHAR(200) NOT NULL,
  Precio_Unitario DECIMAL(10,2) NOT NULL
);

CREATE TABLE Pedido(
  Id_Pedido INT AUTO_INCREMENT PRIMARY KEY,
  Id_Cte INT NOT NULL,
  Fecha_Pedido DATE NOT NULL DEFAULT CURRENT_DATE,
  FOREIGN KEY (Id_Cte) REFERENCES Cliente(Id_Cte) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Detalle_Pedido(
  Id_Pedido INT NOT NULL,
  Id_Producto INT NOT NULL,
  Cantidad_Productos INT NOT NULL CHECK (Cantidad_Productos>0),
  PRIMARY KEY (Id_Pedido,Id_Producto),
  FOREIGN KEY (Id_Pedido) REFERENCES Pedido(Id_Pedido) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (Id_Producto) REFERENCES Producto(Id_Producto) ON UPDATE CASCADE ON DELETE RESTRICT
);
